id: P579296E4
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: it
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    317d3762c34446c9ae9e93364deee7e0:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    04a4c3142c1340bc948304419b2a2c5c:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    b7bb33afb94c47858dca3ead20ec64bc:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    4e7e861588734fb8b1b5a8d7d7e57b88:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    baaadd79aedd4a6cb22c1f93171cab24:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    c152e26b40184dbeb8eeccd28f17ded4:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    bea07537c6e14e7daf08b99e62cfa108:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    9a857580cb5845cda10f49839e69c4e6:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    5017d15783aa4dea9766b281cae7db26:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    1ec6eab103d44899819fb92828fd79c8:
      title: The Lament of Rudra
      parent: Confession
    56cb3970d9f84e1da0ad544b70db8e1c:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    d2169b25d26a453ca72797dd5fb56318:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    874268350f9444f08c2b025073659116:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    1e815991999d4242916ce68cbf7eee3c:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    36d7c0f3a77b4d6aae534f292947ef5a:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    6472a6940b294ba5ac0c78485e1fd72a:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    c754231aeebf465b8f1102cc9f126d3a:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    705651b5e4db42899be76745ba54c745:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    9ed6ae7542184fa39e7772046d0fb2f9:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    65fe9294edd44e12a89dd055a937635d:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    a05478bbdcc84ce1b72c0c7e46476be7:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    240147833bd9455cb8bdbe0b3b613093:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    e1caf9cb630c49788bebd0afabac0e65:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    ba5e293334974595822ad298ab74c0dd:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    08816687f6f947e4856f253bf4e706e3:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    b13836ae8e9640019f595c42b7ee05a4:
      title: The Twenty-Eight Commitments
      parent: Tantra
    8177a2a7e7dc4e34b93db8f1bf1916f0:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.943790'
last_modified_at: '2022-02-28T22:46:47.943793'
